ALTER TABLE CASTROLE DROP FOREIGN KEY FK_CASTROLE_MOVIEACTEDIN_ID;
ALTER TABLE CASTROLE DROP FOREIGN KEY FK_CASTROLE_ACTORINMOVIE_ID;
ALTER TABLE COMMENT DROP FOREIGN KEY FK_COMMENT_REVIEWER_ID;
ALTER TABLE COMMENT DROP FOREIGN KEY FK_COMMENT_MOVIEREVIEWED_ID;

DROP TABLE USER;
DROP TABLE ACTOR;
DROP TABLE CASTROLE;
DROP TABLE COMMENT;
DROP TABLE MOVIE;
