CREATE TABLE USER (ID INTEGER AUTO_INCREMENT NOT NULL,
    DATEOFBIRTH DATE, EMAIL VARCHAR(255),
    FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255),
    PASSWORD VARCHAR(255), USERNAME VARCHAR(255),
    PRIMARY KEY (ID));

CREATE TABLE ACTOR (ID INTEGER AUTO_INCREMENT NOT NULL,
    DATEOFBIRTH DATE, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255),
    PRIMARY KEY (ID));

CREATE TABLE CASTROLE (ID INTEGER AUTO_INCREMENT NOT NULL,
    CHARACTERNAME VARCHAR(255), ACTORINMOVIE_ID INTEGER, MOVIEACTEDIN_ID INTEGER,
    PRIMARY KEY (ID));

CREATE TABLE COMMENT (ID INTEGER AUTO_INCREMENT NOT NULL,
    COMMENT VARCHAR(255), DATECOMMENTED DATE, STARS INTEGER,
    MOVIEREVIEWED_ID INTEGER, REVIEWER_ID INTEGER,
    PRIMARY KEY (ID));

CREATE TABLE MOVIE (ID INTEGER AUTO_INCREMENT NOT NULL,
    POSTERIMAGE VARCHAR(255), RELEASEDATE DATE, TITLE VARCHAR(255),
    PRIMARY KEY (ID));

ALTER TABLE CASTROLE ADD CONSTRAINT
FK_CASTROLE_MOVIEACTEDIN_ID FOREIGN KEY (MOVIEACTEDIN_ID) REFERENCES MOVIE (ID);
ALTER TABLE CASTROLE ADD CONSTRAINT
FK_CASTROLE_ACTORINMOVIE_ID FOREIGN KEY (ACTORINMOVIE_ID) REFERENCES ACTOR (ID);
ALTER TABLE COMMENT ADD CONSTRAINT
FK_COMMENT_REVIEWER_ID FOREIGN KEY (REVIEWER_ID) REFERENCES USER (ID);
ALTER TABLE COMMENT ADD CONSTRAINT
FK_COMMENT_MOVIEREVIEWED_ID FOREIGN KEY (MOVIEREVIEWED_ID) REFERENCES MOVIE (ID);
